name: backend-cd

on:
  workflow_run:
    workflows: [ backend-ci ]        # must match the 'name:' above
    types: [ completed ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # 1) Azure login via OIDC
      - uses: azure/login@v2
        with:
          client-id:      ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:      ${{ secrets.AZURE_TENANT_ID }}
          subscription-id:${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 2) Deploy the new image to Container Apps
      - name: Deploy to Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          resourceGroup:      careerstudio-rg
          containerAppName:   careerstudio-api
          imageToDeploy:      ${{ github.event.workflow_run.outputs.image }}
