name: backend-ci

on:
  push:
    paths:
      - 'backend/**'                 # run when backend code or Dockerfile changes
    branches: [ main ]
  pull_request:
    paths: [ 'backend/**' ]

permissions:
  id-token: write                    # OIDC login
  contents: read

env:
  REGISTRY: careerstudioacr.azurecr.io
  IMAGE_NAME: careerstudio-api       # will be REGISTRY/IMAGE_NAME:<sha>

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend   # all shell steps start in backend/

    outputs:
      image: ${{ steps.meta.outputs.image }}

    steps:
      # 1) Checkout (including sub-modules)
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # 2) Azure login via OIDC
      - uses: azure/login@v2
        with:
          client-id:      ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:      ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 3) Buildx
      - uses: docker/setup-buildx-action@v3

      # 4) Build & push image
      - name: Build and push
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} .
          docker push  $REGISTRY/$IMAGE_NAME:${{ github.sha }}

      # 5) Emit image reference for the CD job
      - name: Export image ref
        id: meta
        run: echo "image=$REGISTRY/$IMAGE_NAME:${{ github.sha }}" >> $GITHUB_OUTPUT
