name: backend-ci

on:
  push:
    paths:
      - 'backend/**'
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  REGISTRY: careerstudioacr.azurecr.io
  IMAGE_NAME: careerstudio-api
  RG: careerstudio-rg
  APP: careerstudio-api

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive }

      - uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to ACR
        run: az acr login --name ${{ env.REGISTRY }}

      - name: Build & push image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} .
          docker push  $REGISTRY/$IMAGE_NAME:${{ github.sha }}

      - name: Deploy to Container Apps
        run: |
          az containerapp update \
            --name ${{ env.APP }} \
            --resource-group ${{ env.RG }} \
            --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --registry-identity system
