name: frontend-cd

on:
  workflow_run:
    workflows: [ frontend-ci ]        # ← must match the build-workflow name
    types:     [ completed ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: fe_dist                # ← must match artifact name in frontend-ci
        path: dist

    - name: Azure Static Web Apps Deploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.STATIC_WEB_APP_TOKEN }}
        action: upload
        app_location: "/"
        output_location: dist
