name: frontend-ci

on:
  push:
    paths:
      - 'frontend/**'            # any change inside the sub-module
      - '.github/workflows/frontend-ci.yml'
  workflow_dispatch:             # allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive    # pulls frontend code

    - name: Install & build
      working-directory: frontend
      run: |
        corepack enable
        pnpm install --frozen-lockfile   # or npm ci / yarn install
        pnpm run build                  # dist/ folder appears

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: fe_dist          # MUST match frontend-cd download name
        path: frontend/dist
